# Generated by Django 6.0.6 on 2026-07-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer')], db_default='applicant', max_length=20),
        ),
    ]
