# Generated by Django 6.0.6 on 2026-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('EMPLOYER', 'Employer')], default='APPLICANT', max_length=20),
        ),
    ]
