# Generated by Django 6.0.6 on 2026-07-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application',
            new_name='applicant',
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
