# Generated by Django 6.0.6 on 2026-07-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'full Time'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract'), ('REMOTE', 'Remote')], max_length=20)),
                ('experience_level', models.CharField(choices=[('FRESHER', 'Fresher'), ('JUNIOR', 'Junior (1-2 years)'), ('MID', 'Mid-Level (3-5 years)'), ('SENIOR', 'Senior (5+ years)')], default='FRESHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('application_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
        ),
    ]
